# Generated by Django 2.0.1 on 2018-03-25 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField()),
                ('doc_type', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('citation', models.CharField(blank=True, max_length=120)),
                ('authors', models.CharField(blank=True, max_length=255)),
                ('full_text_link', models.CharField(blank=True, max_length=255)),
                ('journal_link', models.CharField(blank=True, max_length=255)),
                ('abstract_link', models.CharField(blank=True, max_length=255)),
                ('arXiv_link', models.CharField(blank=True, max_length=255)),
                ('ADS_link', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['sub_category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='PaperCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('display_order', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PaperSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('display_order', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='papers.PaperCategory')),
            ],
            options={
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='papers.PaperSubCategory'),
        ),
    ]
