# Generated by Django 2.0.1 on 2018-03-23 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('link', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('low_level', models.CharField(max_length=3)),
                ('high_level', models.CharField(blank=True, max_length=3)),
                ('callers', models.CharField(blank=True, max_length=120)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calling.Event')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
